### ISSUE TITLE
Consider using `deps-info` for `neil new` implementation

### ISSUE THREAD

**Issue by rads** [babashka/neil#116]
I needed to use the same `tools.deps` inference for [`bbin`](https://github.com/rads/bbin) so I moved the code to a shared library:

https://github.com/rads/deps-infer

I suggest we add a dependency for this lib in `neil` and update the `neil new` implementation to use this.

I plan to maintain `deps-infer` going forward since it's a useful library on its own without `bbin` or `neil`.

```
bb --config <(echo "{:deps $(deps-infer --lib io.github.rads/watch)}") \
  -e "(require 'rads.watch) (rads.watch/print-help nil)"
```

**Comment by borkdude** [comment]
@rads Hmm, I already have a library with the same name but with a different purpose: https://github.com/borkdude/deps-infer.

**Comment by rads** [comment]
@borkdude: Ah, I didn't know about that one! I can change the name if that's the main blocker here.

**Comment by rads** [comment]
Woops, wrong button!

**Comment by rads** [comment]
I should clarify that I plan to change the name regardless of whether we use the library for `neil`. Definitely want to avoid any conflicts with your library.

**Comment by borkdude** [comment]
On the other hand, `borkdude/deps-infer` isn't very actively developed and used, so maybe it's not a big deal. Coming up with a good unique name is hard.

**Comment by borkdude** [comment]
Other than that, I don't see a problem, other than maybe some redundant code in the library which could slow down neil's startup time. I do prefer keeping neil's deps as lean as possible to ensure good startup and bb compatibility.

**Comment by rads** [comment]
@borkdude:
> I do prefer keeping neil's deps as lean as possible to ensure good startup and bb compatibility.
I agree. I think I can keep any extra stuff out of `neil` by splitting the namespaces and `:deps/root` as needed.

**Comment by rads** [comment]
I've created a duplicate issue of https://github.com/babashka/neil/issues/79 in https://github.com/rads/deps-info/issues/1. This means I can implement the GitLab/Bitbucket/Beanstalk/Sourcehut integration there and both `bbin` and `neil` will be able to use it.

Going to hold off on using `deps-info` for `neil` until https://github.com/rads/deps-info/issues/1 is done first.

**Comment by rads** [comment]
I'm moving the `deps-info` code inline into `bbin` so I'm going to close this issue for now.
