### ISSUE TITLE
neil adds trailing whitespace

### ISSUE THREAD

**Issue by dakra** [babashka/neil#13]
After `neil add build` the added entry in deps.edn contains trailing whitespace.
![image](https://user-images.githubusercontent.com/574659/140511194-d91c091f-764d-4358-81a3-24e9f5030dbc.png)

**Comment by borkdude** [comment]
Thanks, will take a look soon, if you don't beat me to it.

**Comment by borkdude** [comment]
Should be fixed.

**Comment by dakra** [comment]
Thanks :)
