### ISSUE TITLE
`neil add dep` erases deps.edn

### ISSUE THREAD

**Issue by akond** [babashka/neil#131]
If I execute `neil add dep com.rpl.specter` then my deps.edn becomes empty.

**Comment by borkdude** [comment]
That's not good! We should probably check for a fully qualified name.

**Comment by akond** [comment]
Here is my `justfile`:
```
akond@akond:~/workspace-test/xxxx$ cat justfile 
DIR:="issue-131"
run:
  rm -rf {{DIR}}
  neil new --name {{DIR}}
  hd {{DIR}}/deps.edn
  cd {{DIR}}; neil add dep com.rpl.specter
  hd {{DIR}}/deps.edn

```
So the result looks :
```
akond@akond:~/workspace-test/xxxx$ just
rm -rf issue-131
neil new --name issue-131
Creating project from org.corfield.new/scratch in issue-131
hd issue-131/deps.edn
00000000  7b 3a 70 61 74 68 73 20  5b 22 73 72 63 22 5d 0a  |{:paths ["src"].|
00000010  20 3a 64 65 70 73 20 20  7b 7d 0a 20 3a 61 6c 69  | :deps  {}. :ali|
00000020  61 73 65 73 20 0a 20 7b  3a 6e 65 69 6c 20 7b 3a  |ases . {:neil {:|
00000030  70 72 6f 6a 65 63 74 20  7b 3a 6e 61 6d 65 20 69  |project {:name i|
00000040  73 73 75 65 2d 31 33 31  2f 69 73 73 75 65 2d 31  |ssue-131/issue-1|
00000050  33 31 7d 7d 7d 7d 0a                              |31}}}}.|
00000057
cd issue-131; neil add dep com.rpl.specter
hd issue-131/deps.edn
00000000  0a                                                |.|
00000001

```
Please, notice, that I use `dep com.rpl.specter` and not `com.rpl/specter`

**Comment by borkdude** [comment]
Yes, you should use the fully qualified symbol, but we should have some error checking for this.

**Comment by borkdude** [comment]
Also please specify the version of neil you are using.

**Comment by akond** [comment]
akond@akond:~/workspace-test/xxxx$ neil --version
neil 0.1.46

**Comment by akond** [comment]
Yes, the repo name is bogus, but I don't think that emptying deps.edn is an adequate response.
And thank you for responding on such a short notice.

**Comment by borkdude** [comment]
> but I don't think that emptying deps.edn is an adequate response

Fully agreed :) This should be fixed.

**Comment by akond** [comment]
Yes, now it keeps the file untouched.

**Comment by borkdude** [comment]
I assume this is fixed. Please leave a message if it's not.
