### ISSUE TITLE
neil add license :name epl1

### ISSUE THREAD

**Issue by borkdude** [babashka/neil#14]
Support adding licenses by downloading them and adding them to a LICENSE file.

**Comment by bobisageek** [comment]
I don't want to open a big rabbit hole here if this is overkill, but github provides a licenses API that could potentially be leveraged here. I'm primarily putting this option out there to maybe pre-empt feature requests for a bunch of different licenses to be added.

Pros:
- license texts (and also name) for a fairly wide variety of licenses (including epl 1.0) can be retrieved from one API
- the license API doesn't require authentication, so it doesn't create any additional dependencies beyond access to the internet in general and github.com in particular

Cons:
- limited to the licenses available from github's API, which will likely change over time (the API doesn't seem to return all available licenses, but the full set is visible at https://github.com/github/choosealicense.com/tree/gh-pages/_licenses)
- UX might be best if users need to supply the license ID as dictated by the github API (e.g. 'epl-1.0', 'apache-2.0') - we could do a map of short names to IDs, but unless we kept up that mapping for all the licenses, it might feel a bit incongruous across license options (e.g. 'epl1' vs 'mpl-2.0').

Is this the kind of thing you were thinking about, or do you prefer a more curated list of licenses?

**Comment by borkdude** [comment]
The use case I have in mind is that in a lot of new projects I start, I usually copy a `LICENSE` file from another project, but `neil add license` could help with that. I'm fine with going with whatever Github offers.
