### ISSUE TITLE
Possibly more intuitive CLI command / subcommand naming?

### ISSUE THREAD

**Issue by teodorlu** [babashka/neil#18]
Working on #16, I didn't find any place to fit in "list available versions for a library" into the current subcommand stucture. Toplevel `add` doesn't fit - we're not adding versions. Yet, listing available versions is very much related to adding a version.

Grouping dependency stuff together makes sense to me. For example:

```bash
# :lib as option - or as the first command
neil dep add :lib org.clojure/clojure
neil dep add org.clojure/clojure

# dep versions subcommand can have same structure.
neil dep versions :lib org.clojure/clojure
neil dep versions org.clojure/clojure
```

Not sure about what to do about the rest of the `add` subcommand. Perhaps just keep it. We woiuld have two ways of adding a dependency (`neil dep add` and `neil add dep`).

**Comment by borkdude** [comment]
I agree that `dep add` is the way to do. We should keep `add dep` for backward compatibility, perhaps we can just "rewrite" `add dep` to `dep add` or so.

**Comment by borkdude** [comment]
Was this already done?

**Comment by teodorlu** [comment]
No - I removed the `neil dep add` entrypoint. Should be a single-line change to add it back.

**Comment by borkdude** [comment]
Do you want to first do this, or do a release with the previous stuff first?

**Comment by teodorlu** [comment]
If you also want the `neil dep add` entrypoint in, I'd be happy to create a tiny second PR :)

**Comment by teodorlu** [comment]
Here: https://github.com/babashka/neil/pull/19
