### ISSUE TITLE
Neil new behaviour different for windows  

### ISSUE THREAD

**Issue by muthuishere** [babashka/neil#189]
neil new io.github.kit-clj/kit deemwar/helloweb is working fine in Linux based machines ,But in windows its not creating packages properly.

Upon investigation, we could see clj-new works well but deps-new is not working well.

I would like to understand,How the Neil new command will be transformed to deps-new

```
neil new io.github.kit-clj/kit deemwar/helloweb

```

for the above command,what will be the equivalent deps-new transformation??

https://github.com/kit-clj/kit/issues/113#issuecomment-1708708556

**Comment by borkdude** [comment]
The code is here: https://github.com/babashka/neil/blob/main/src/babashka/neil/new.clj
You can perhaps add some debugging in that file and try it out. But perhaps it's better to try deps-new directly to see if there's an issue with deps-new itself.

**Comment by muthuishere** [comment]
Thanks

**Comment by borkdude** [comment]
Did you manage to figure it out?

**Comment by muthuishere** [comment]
Yes the issue is in the template,. Added a PR for them
