### ISSUE TITLE
suggestion: use DEPS_CLJ_TOOLS_DIR to detect DEPS_CLJ_TOOLS_VERSION

### ISSUE THREAD

**Issue by icp1994** [babashka/neil#207]
If a user has set `DEPS_CLJ_TOOLS_DIR`, I think they would almost certainly want to use the version corresponding to `${DEPS_CLJ_TOOLS_DIR}/libexec/clojure-tools-${version}.jar`. Currently they have to also provide `DEPS_CLJ_TOOLS_VERSION` to resolve conflict against the hard-coded version. This is a minor inconvenience for system wide installations in distros as when you update clojure to a more recent version, you will also need to update your `~/.profile` or similar with the respective `DEPS_CLJ_TOOLS_VERSION`.

**Comment by borkdude** [comment]
I'm not sure how this exactly relates to neil specifically rather than deps.clj?

**Comment by icp1994** [comment]
Oh, right - made the issue in wrong repo.
