### ISSUE TITLE
Allow "pinning" a dependency, so it is not changed on global "upgrade"

### ISSUE THREAD

**Issue by chromalchemy** [babashka/neil#227]
Allow `:neil/pinned true` on a dependency to prevend it getting bumped on `neil dep upgrade`

Case: I started getting errors in from nextjournal.markdown, apparently from from a java upgrade. Per an older reccomendation, if (in deps.edn) i point the dep to a Sha on a branch with a patch, it works. But every time I run the neil upgrade, it bumps that Sha to another one (presumably older, but on the main branch?), and the errors return if I dont revert the change.

**Comment by borkdude** [comment]
LGTM. @teodorlu if you want, you can take this one, else I'll look at this soon!

**Comment by teodorlu** [comment]
I'll have a look 👌
