### ISSUE TITLE
neil dep upgrade still upgrades git dep

### ISSUE THREAD

**Issue by borkdude** [babashka/neil#229]
Repro:

``` clojure
{:deps {io.github.nextjournal/markdown {:git/sha "6683c48dfdb23404a23057817b6ac3acf0310bca" :neil/pinned true}}}
```

Run `neil dep upgrade` and it upgrades the dep.

**Comment by teodorlu** [comment]
I'll have a look.

**Comment by teodorlu** [comment]
I failed to reproduce the error with this test: https://github.com/teodorlu/neil/commit/e75658093f479d761e3201b67dc0a28def58c454

I'll put some more effort into it later.

**Comment by borkdude** [comment]
I just tested with the CLI in a real project

https://www.michielborkent.nl
https://www.eetvoorjeleven.nu

**Comment by borkdude** [comment]
Also `:mvn/version` dep is still upgrading, weirdly enough

**Comment by teodorlu** [comment]
Ok. Compiled script is in sync with source, right? (`bb gen-script`)

**Comment by borkdude** [comment]
I've tested with the brew-installed script, but I'll re-test with the local script

**Comment by borkdude** [comment]
Hmm, with the local script, it does work like expected. Seems like a release problem then...
