### ISSUE TITLE
Problems with `neil dep search` and `neil dep versions`

### ISSUE THREAD

**Issue by teodorlu** [babashka/neil#24]
as far as I can tell:

1. both `dep versions` and dep search are broken on master
2. `dep versions` works on 0.0.23
3. `dep search` on 0.0.23 works when searching for `hiccup`, but fails when searching for `org.clojure/clojure`

**Comment by borkdude** [comment]
@yisraeldov Could be a result of the latest refactor commit. Should we revert that? `org.clojure/clojure` could be explained because that is not on clojars.

**Comment by borkdude** [comment]
@teodorlu I am testing `neil dep versions` with the script on master nad it works for me:

```
$ ./neil dep versions cheshire/cheshire
:lib cheshire/cheshire :version 5.10.2
:lib cheshire/cheshire :version 5.10.1
:lib cheshire/cheshire :version 5.10.0
```

`dep search` also worked for me:

```
$ ./neil dep search cheshire
:lib cheshire/cheshire :version 5.10.2
:lib cambium/cambium.codec-cheshire :version 1.0.0
:lib com.vgeshel/cheshire :version 5.3.1.2
```

Can you provide an example that doesn't work for you and still worked with v0.0.23?

**Comment by teodorlu** [comment]
> Can you provide an example that doesn't work for you and still worked with v0.0.23?

Today, I cannot.

This is weird. Perhaps Clojars had some problems yesterday, and this was unrelated to `neil`.

**Comment by teodorlu** [comment]
We do hit a null pointer exception when searching for `hiccup/hiccup` and other things with a slash in it. Slashes do not seem to be allowed in the [Clojars Query Syntax][clojars-query], but that behavior is the same on `main` and `v0.0.23`.

[clojars-query]: https://github.com/clojars/clojars-web/wiki/Search-Query-Syntax
