### ISSUE TITLE
Neil.el doesn't work if `neil-executable-path` is set to command with arguments, e.g. `clj -M:neil`

### ISSUE THREAD

**Issue by a13** [babashka/neil#245]
I want to use neil via `clj` cli command, so I set `neil-executable-path` to `neil-executable-path`

# expected result

`M-x neil-find-clojure-package` works

# actual result

I get "Cannot find 'neil' cmd-line utility!" error. (because `executable-find` accepts only command name without arguments)

**Comment by borkdude** [comment]
Is this a question or a bug report? What do you expect us to do about this?

**Comment by a13** [comment]
@borkdude Sorry if it wasn't very clear, I added more details to clarify the issue

**Comment by a13** [comment]
btw, the quick search https://github.com/search?q=neil-executable-path&type=code can't find any person setting it (sure, not everyone keeps their Emacs config on GU), so probably we can avoid calling `executable-find` for the customized value completely?

**Comment by borkdude** [comment]
I'll wait for @agzam's reply since I'm not that knowledgable about elisp.
I guess a workaround for now would be to write a bash script (or .bat script on Windows) that calls clj -M:neil.
Any reason you're not running this with bb?

**Comment by agzam** [comment]
Hey friends. It looks like it ain't so straightforward as I thought it would be.

I'm currently trying to investigate why "clj -M" call is failing weirdly. For whatever reason, this: 

```
(shell-command-to-string "/usr/bin/clj -M:neil dep search reitit")
```

fails for me with:

```
"Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
dep (No such file or directory)

Full report at:
/tmp/clojure-13551916015830764356.edn
"
```

I'm trying to find alternatives.

**Comment by agzam** [comment]
Update: The PR is out. Please give it a gander. I'm not sure what that weird bug was that I caught before, I'll keep an eye for it.

**Comment by a13** [comment]
> I'll wait for @agzam's reply since I'm not that knowledgable about elisp. I guess a workaround for now would be to write a bash script (or .bat script on Windows) that calls clj -M:neil. Any reason you're not running this with bb?

No particular reason, except that the bb version was in the "Manual" section of the README.

**Comment by borkdude** [comment]
@a13 I stronly recommend running with babashka since this starts up much quicker and gives a better UX in emacs.
If you use [bbin](https://github.com/babashka/bbin/), you can also use `bbin install io.github.babashka/neil`

**Comment by a13** [comment]
> If you use [bbin](https://github.com/babashka/bbin/)

Well, it looks like the time has finally come. Probably the last time I looked at it, there wasn't a brew recipe, and, as I said, avoid manual installation. Thanks!
