### ISSUE TITLE
Can't run Neil using clojure cli (using a global alias from README) in the neil source code directory

### ISSUE THREAD

**Issue by a13** [babashka/neil#246]
`babashka v1.3.191`

`Clojure CLI version 1.12.0.1479`

`neil v0.3.68`

**problem**

Can't run Neil using clojure cli (using a global alias from README) in the neil source code directory.

**repro**

1. put 

``` clojure
:neil {:deps {io.github.babashka/neil {:git/tag "v0.3.68"
                                       :git/sha "78ffab1"}}
       :main-opts ["-m" "babashka.neil"]}
```
alias into ~/.clojure/deps.edn

2. run `clj -M:neil dep search foo` from the directory with neil source code (or any other directory containing deps.edn file with :neil alias)

**actual behavior**

```sh
"Execution error (FileNotFoundException) at java.io.FileInputStream/open0 (FileInputStream.java:-2).
dep (No such file or directory)

Full report at:
/tmp/clojure-11707584721737191941.edn
"
```

**expected behavior**

`clj -M:neil dep search foo` returns the list of libraries

It looks like the problem is that the `:neil` alias from `deps.edn` overrides the global one. Can we change one of these to something else?

**Comment by borkdude** [comment]
This is just standard clojure CLI behavior, an alias in the local directory overrides the global alias. Unfortunately we can't change this convention since it's a convention used by neil itself to store the version information of a project in there. What we could do is add the main opts in there so you can run the alias in the local project as well.

**Comment by a13** [comment]
> What we could do is add the main opts in there so you can run the alias in the local project as well.

I think mentioning this in the README would be good enough.

**Comment by borkdude** [comment]
> I think mentioning this in the README would be good enough.

PR welcome
