### ISSUE TITLE
add --version flag for cmd

### ISSUE THREAD

**Issue by agzam** [babashka/neil#26]

**Comment by borkdude** [comment]
PR welcome.

**Comment by teodorlu** [comment]
Any ideas on how to best achieve this?

We have the `version.txt` file. Do we want to embed this file into the `neil` binary when running `gen-script`? Should we embed the time of build too?

Do we also want Git SHA?

**Comment by borkdude** [comment]
Just the version for now. Yeah, I do something similar in deps.clj

https://github.com/borkdude/deps.clj

**Comment by teodorlu** [comment]
https://github.com/babashka/neil/pull/39

Should solve this!
