### ISSUE TITLE
Some kind of messed up dependency resolution

### ISSUE THREAD

**Issue by agzam** [babashka/neil#40]
I removed `~/.m2/repository` (for unrelated reasons), and now I cannot run neil anymore. I got the latest `main`; ran `bb run gen-script`, and then tried doing: `./neil dep search foo`. It's throwing this:

    ----- Error --------------------------------------------------------------------
    Type:     java.nio.file.NoSuchFileException
    Message:  /Users/ag/.m2/repository/borkdude/rewrite-edn/0.0.2/rewrite-edn-0.0.2.jar
    Location: /Users/ag/sandbox/babashka_neil/./neil:13:1

    ----- Context ------------------------------------------------------------------
    9:
    10: (ns babashka.neil
    11:   {:no-doc true})
    12:
    13: (require '[babashka.curl :as curl]
        ^--- /Users/ag/.m2/repository/borkdude/rewrite-edn/0.0.2/rewrite-edn-0.0.2.jar
    14:          '[babashka.fs :as fs]
    15:          '[borkdude.rewrite-edn :as r]
    16:          '[cheshire.core :as cheshire]
    17:          '[clojure.edn :as edn]
    18:          '[clojure.string :as str])

    ----- Stack trace --------------------------------------------------------------
    sun.nio.fs.UnixFileAttributeViews/Basic      - <built-in>
    java.util.zip.ZipFile/Source                 - <built-in>
    java.util.zip.ZipFile/CleanableResource      - <built-in>
    babashka.impl.classpath/path-from-jar        - <built-in>
    babashka.impl.classpath.Loader/fn--17130     - <built-in>
    clojure.core/some                            - <built-in>
    babashka.impl.classpath/source-for-namespace - <built-in>
    babashka.main/exec/load-fn--34829            - <built-in>
    babashka.neil                                - /Users/ag/sandbox/babashka_neil/./neil:13:1
    
I'm not sure what's going on. Running `clj -Stree` shows this:

    Picked up JAVA_TOOL_OPTIONS: -Dapple.awt.UIElement=true
    org.clojure/clojure 1.11.1
    . org.clojure/spec.alpha 0.3.218
    . org.clojure/core.specs.alpha 0.2.62
    babashka/babashka.curl 0.1.0
    babashka/fs 0.1.1
    rewrite-clj/rewrite-clj 1.0.699-alpha
    . org.clojure/tools.reader 1.3.6
    borkdude/rewrite-edn 0.1.0
    X rewrite-clj/rewrite-clj 1.0.572-alpha :use-top                <---- see this? 
    cheshire/cheshire 5.10.1
    . com.fasterxml.jackson.core/jackson-core 2.12.4
    . com.fasterxml.jackson.dataformat/jackson-dataformat-smile 2.12.4
        . com.fasterxml.jackson.core/jackson-databind 2.12.4
        . com.fasterxml.jackson.core/jackson-annotations 2.12.4
        . com.fasterxml.jackson.core/jackson-core 2.12.4
        . com.fasterxml.jackson.core/jackson-core 2.12.4
    . com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.12.4
        . com.fasterxml.jackson.core/jackson-databind 2.12.4
        . com.fasterxml.jackson.core/jackson-core 2.12.4
    . tigris/tigris 0.1.2
    
Can someone tell me what's happening? What have I screwed up on my machine?

**Comment by agzam** [comment]
I tried bumping up the versions of `rewrite-clj/rewrite-clj` and `borkdude/rewrite-edn` in deps.edn file - that didn't seem to fix this.

**Comment by borkdude** [comment]
@agzam You can try `bb --force $(which neil)`

**Comment by borkdude** [comment]
And if that doesn't work: `rm -rf ~/.clojure/.cpcache` + `rm -rf .cpcache`

**Comment by agzam** [comment]
yup, removing ~/.clojure/.cpcache has worked. btw. it looks like the corrupt global .cpcache may even break brew-installed script.
I panicked because it broke both the local script in the repo and the one installed via brew.

**Comment by borkdude** [comment]
This is because both scripts use tools deps to download borkdude.rewrite-edn, although we could maybe inline that using `uberscript`.
