### ISSUE TITLE
Add `bb dev` task to auto-build `neil` script

### ISSUE THREAD

**Issue by rads** [babashka/neil#82]
I've been using the following command for `neil` development to re-run the `bb gen-script` task when a file changes:
```
find . -iname '*.clj' -o -iname 'prelude' | entr -s 'bb gen-script && date'
```
Would it be helpful to add a `bb watch-script` task so this is built-in to the `neil` repo? It would be nice to not have to use `entr` for this.

If so, I'm assuming [pod-babashka-fswatcher](https://github.com/babashka/pod-babashka-fswatcher) would be preferred over [pod-babashka-filewatcher](https://github.com/babashka/pod-babashka-filewatcher) for implementation since it has more recent updates. **Edit:** Actually I see now that fswatcher does not have a `brew` formula yet, so I'm not so sure.

**Comment by borkdude** [comment]
Yes, we can do a `bb dev` task I think which does that.

**Comment by rads** [comment]
Great! I was just reading through the docs on fswatcher and I found the `:pods` example for babashka >=0.8.0:
```clojure
:pods {org.babashka/fswatcher {:version "0.0.3"}}
```
Is that what you would recommend to implement this?

**Comment by borkdude** [comment]
Yeah, I think that works.

**Comment by rads** [comment]
Excellent, thanks!
