### ISSUE TITLE
Alias option ignored in neil dep add library --alias alias

### ISSUE THREAD

**Issue by kees-** [babashka/neil#91]
Am I just missing something? I'm unable to target custom aliases when adding dependencies to a `deps.edn`.

### Expected behavior-
`neil dep add vlaaad/reveal --alias :reveal` would add the latest version of reveal to an alias `:reveal` under its `:extra-deps`

### Apparent behavior-
The dependency is added to `:deps`.

---

<details>
<summary>These commands are working as expected:</summary>

- ✅ `neil add nrepl --alias :nrepl-custom-alias`
- ✅ `neil add kaocha --alias :kaocha-custom`
- etc.
- ✅ `neil add dep vlaaad/reveal --version (custom-version)`
- ✅ `             "             :version (custom-version)`
- ✅ `             "             --as different-name`

</details>
<details>
<summary>In these commands, `--alias` seems to be ignored:</summary>

- ❌ `neil add dep vlaaad/reveal --alias :reveal`
- ❌ `             "             --alias reveal`
- ❌ `             "             --alias "reveal"`

</details>

Same goes with all versions of the command with `neil dep add`.

So, the `alias` flag is working both as a CLI flag and a keyword for all commands except `add dep`. All other flags for `add dep` besides `alias` also work.

---

Taking a look at neil.clj, [dep-add](https://github.com/babashka/neil/blob/main/src/babashka/neil.clj#L304) is the only fn that adds dependencies and doesn't call [add-alias](https://github.com/babashka/neil/blob/main/src/babashka/neil.clj#L105) or check for the keyword.

**Comment by borkdude** [comment]
Good catch! Do you want us to fix this or would you like to work on a PR yourself?

**Comment by kees-** [comment]
Thanks for the opportunity to try! I'll either open a pr or comment back!

**Comment by rads** [comment]
@borkdude: Looks like we can close this issue now that #92 and https://github.com/babashka/neil/pull/104 are merged.

**Comment by borkdude** [comment]
Somehow this still doesn't work for me.

When I run: `neil dep add cheshire/cheshire --alias dude` cheshire gets added as a top level dependency.

**Comment by borkdude** [comment]
@bsless was running into this issue this morning

**Comment by kees-** [comment]
Hey there, oy, I haven't been lucky taking a stab at what should have been a one-shot fix! Sorry to have prolonged this issue!

Where were you guys running it from? I see that [babashka/homebrew-brew doesn't have formulae files for the two most recent tags](https://github.com/babashka/homebrew-brew/tree/main/Formula). So, the version I have installed from brew is 0.1.43 instead of 0.1.45 which I see was released a week before we addressed this issue.

I just tried running from the tag hosted on github and the alias flag worked for me. Or were you having issues with running the current code i.e from the repo?

**Comment by kees-** [comment]
Just cross-referenced this as well with the new bbin (cool!):

```bash
brew uninstall neil # v0.1.43 from homebrew
brew install babashka/brew/bbin
echo -e '\npath+=(/Users/kees/.babashka/bbin/bin)' >> .zshrc && exec zsh
bbin install io.github.babashka/neil
neil --version # => neil 0.1.45

clj -Tnew lib :name test/test && cd test
neil dep add cheshire/cheshire --alias json
cat deps.edn
```
=>
```clj
{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.11.1"}}
 :aliases
 {:test
  {:extra-paths ["test"]
   :extra-deps {org.clojure/test.check {:mvn/version "1.1.1"}
                io.github.cognitect-labs/test-runner
                {:git/tag "v0.5.1" :git/sha "dfb30dd"}}}
  :build {:deps {io.github.seancorfield/build-clj
                 {:git/tag "v0.8.2" :git/sha "0ffdb4c"}}
          :ns-default build}
  :json {:extra-deps {cheshire/cheshire {:mvn/version "5.11.0"}}}}}
```

And it does seem to work fine.

Hadn't known this but a duplicate command installed via brew appears to override what's set in the path, is it possible that's what's going on?

**Comment by borkdude** [comment]
Aaaah, the brew package was behind. My bad.

**Comment by kees-** [comment]
Np, your projects have grown to quite an ecosystem! I'm sure there are lots of moving parts. Thanks to you and your collaborators for all the great work
